name: validate-devschema
on:
  pull_request:
    paths:
      - '**/devcontainer.json'
  push:
    branches:
      - main
    paths:
      - '**/devcontainer.json'

jobs:
  validate-devschema:
    uses: jdevto/actions/.github/workflows/validate-devschema.yml@main
    with:
      verbose: true
